// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file sleepers/v1/accounts.proto (package sleepers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { CharacterState } from "./world_pb";
import { file_sleepers_v1_world } from "./world_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sleepers/v1/accounts.proto.
 */
export const file_sleepers_v1_accounts: GenFile = /*@__PURE__*/
  fileDesc("ChpzbGVlcGVycy92MS9hY2NvdW50cy5wcm90bxILc2xlZXBlcnMudjEicQoHQWNjb3VudBIMCgR0aWVyGAEgASgJEgwKBHJvbGUYAiABKAkSFwoPY2hhcmFjdGVyX3Nsb3RzGAMgASgNEjEKCmNoYXJhY3RlcnMYBCADKAsyHS5zbGVlcGVycy52MS5DaGFyYWN0ZXJTdW1tYXJ5InwKEENoYXJhY3RlclN1bW1hcnkSCgoCaWQYASABKAMSDAoEbmFtZRgCIAEoCRISCgpoYXNfcGxheWVkGAMgASgIEioKBXN0YXRlGAQgASgOMhsuc2xlZXBlcnMudjEuQ2hhcmFjdGVyU3RhdGUSDgoGb25saW5lGAUgASgIIiYKFkNyZWF0ZUNoYXJhY3RlclJlcXVlc3QSDAoEbmFtZRgBIAEoCSIgCg1FcnJvclJlc3BvbnNlEg8KB21lc3NhZ2UYASABKAlCNFoyc2xlZXBlcnMvc2VydmVyL2ludGVybmFsL3BiL3NsZWVwZXJzL3YxO3NsZWVwZXJzdjFiBnByb3RvMw", [file_sleepers_v1_world]);

/**
 * Account is the signed-in player's account and characters.
 *
 * @generated from message sleepers.v1.Account
 */
export type Account = Message<"sleepers.v1.Account"> & {
  /**
   * free, beta or paid (ADR 044)
   *
   * @generated from field: string tier = 1;
   */
  tier: string;

  /**
   * player, moderator or admin
   *
   * @generated from field: string role = 2;
   */
  role: string;

  /**
   * how many characters the tier allows
   *
   * @generated from field: uint32 character_slots = 3;
   */
  characterSlots: number;

  /**
   * @generated from field: repeated sleepers.v1.CharacterSummary characters = 4;
   */
  characters: CharacterSummary[];
};

/**
 * Describes the message sleepers.v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> = /*@__PURE__*/
  messageDesc(file_sleepers_v1_accounts, 0);

/**
 * CharacterSummary is what the character-select screen shows.
 *
 * @generated from message sleepers.v1.CharacterSummary
 */
export type CharacterSummary = Message<"sleepers.v1.CharacterSummary"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * false: never been in the world yet
   *
   * @generated from field: bool has_played = 3;
   */
  hasPlayed: boolean;

  /**
   * where it was left, if it has played
   *
   * @generated from field: sleepers.v1.CharacterState state = 4;
   */
  state: CharacterState;

  /**
   * in the world right now
   *
   * @generated from field: bool online = 5;
   */
  online: boolean;
};

/**
 * Describes the message sleepers.v1.CharacterSummary.
 * Use `create(CharacterSummarySchema)` to create a new message.
 */
export const CharacterSummarySchema: GenMessage<CharacterSummary> = /*@__PURE__*/
  messageDesc(file_sleepers_v1_accounts, 1);

/**
 * @generated from message sleepers.v1.CreateCharacterRequest
 */
export type CreateCharacterRequest = Message<"sleepers.v1.CreateCharacterRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message sleepers.v1.CreateCharacterRequest.
 * Use `create(CreateCharacterRequestSchema)` to create a new message.
 */
export const CreateCharacterRequestSchema: GenMessage<CreateCharacterRequest> = /*@__PURE__*/
  messageDesc(file_sleepers_v1_accounts, 2);

/**
 * @generated from message sleepers.v1.ErrorResponse
 */
export type ErrorResponse = Message<"sleepers.v1.ErrorResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message sleepers.v1.ErrorResponse.
 * Use `create(ErrorResponseSchema)` to create a new message.
 */
export const ErrorResponseSchema: GenMessage<ErrorResponse> = /*@__PURE__*/
  messageDesc(file_sleepers_v1_accounts, 3);

