// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file sleepers/v1/ping.proto (package sleepers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sleepers/v1/ping.proto.
 */
export const file_sleepers_v1_ping: GenFile = /*@__PURE__*/
  fileDesc("ChZzbGVlcGVycy92MS9waW5nLnByb3RvEgtzbGVlcGVycy52MSIVCgRQaW5nEg0KBW5vbmNlGAEgASgNIhUKBFBvbmcSDQoFbm9uY2UYASABKA1CNFoyc2xlZXBlcnMvc2VydmVyL2ludGVybmFsL3BiL3NsZWVwZXJzL3YxO3NsZWVwZXJzdjFiBnByb3RvMw");

/**
 * Ping is sent by either side to check the connection is alive.
 * The receiver answers with a Pong carrying the same nonce.
 *
 * @generated from message sleepers.v1.Ping
 */
export type Ping = Message<"sleepers.v1.Ping"> & {
  /**
   * @generated from field: uint32 nonce = 1;
   */
  nonce: number;
};

/**
 * Describes the message sleepers.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_sleepers_v1_ping, 0);

/**
 * @generated from message sleepers.v1.Pong
 */
export type Pong = Message<"sleepers.v1.Pong"> & {
  /**
   * @generated from field: uint32 nonce = 1;
   */
  nonce: number;
};

/**
 * Describes the message sleepers.v1.Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export const PongSchema: GenMessage<Pong> = /*@__PURE__*/
  messageDesc(file_sleepers_v1_ping, 1);

