// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file glyph/v1/ping.proto (package glyph.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file glyph/v1/ping.proto.
 */
export const file_glyph_v1_ping: GenFile = /*@__PURE__*/
  fileDesc("ChNnbHlwaC92MS9waW5nLnByb3RvEghnbHlwaC52MSIVCgRQaW5nEg0KBW5vbmNlGAEgASgNIhUKBFBvbmcSDQoFbm9uY2UYASABKA1CK1opZ2x5cGgvc2VydmVyL2ludGVybmFsL3BiL2dseXBoL3YxO2dseXBodjFiBnByb3RvMw");

/**
 * Ping is sent by either side to check the connection is alive.
 * The receiver answers with a Pong carrying the same nonce.
 *
 * @generated from message glyph.v1.Ping
 */
export type Ping = Message<"glyph.v1.Ping"> & {
  /**
   * @generated from field: uint32 nonce = 1;
   */
  nonce: number;
};

/**
 * Describes the message glyph.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_glyph_v1_ping, 0);

/**
 * @generated from message glyph.v1.Pong
 */
export type Pong = Message<"glyph.v1.Pong"> & {
  /**
   * @generated from field: uint32 nonce = 1;
   */
  nonce: number;
};

/**
 * Describes the message glyph.v1.Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export const PongSchema: GenMessage<Pong> = /*@__PURE__*/
  messageDesc(file_glyph_v1_ping, 1);

