// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file glyph/v1/world.proto (package glyph.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file glyph/v1/world.proto.
 */
export const file_glyph_v1_world: GenFile = /*@__PURE__*/
  fileDesc("ChRnbHlwaC92MS93b3JsZC5wcm90bxIIZ2x5cGgudjEiIAoIUG9zaXRpb24SCQoBeBgBIAEoBRIJCgF5GAIgASgFIkQKBFJvb20SDQoFd2lkdGgYASABKA0SDgoGaGVpZ2h0GAIgASgNEh0KBXRpbGVzGAMgAygOMg4uZ2x5cGgudjEuVGlsZSJ0CglDaGFyYWN0ZXISCgoCaWQYASABKA0SDAoEbmFtZRgCIAEoCRIkCghwb3NpdGlvbhgDIAEoCzISLmdseXBoLnYxLlBvc2l0aW9uEicKBXN0YXRlGAQgASgOMhguZ2x5cGgudjEuQ2hhcmFjdGVyU3RhdGUq4AEKCURpcmVjdGlvbhIZChVESVJFQ1RJT05fVU5TUEVDSUZJRUQQABITCg9ESVJFQ1RJT05fTk9SVEgQARIYChRESVJFQ1RJT05fTk9SVEhfRUFTVBACEhIKDkRJUkVDVElPTl9FQVNUEAMSGAoURElSRUNUSU9OX1NPVVRIX0VBU1QQBBITCg9ESVJFQ1RJT05fU09VVEgQBRIYChRESVJFQ1RJT05fU09VVEhfV0VTVBAGEhIKDkRJUkVDVElPTl9XRVNUEAcSGAoURElSRUNUSU9OX05PUlRIX1dFU1QQCCpuCgpTcGVlY2hNb2RlEhsKF1NQRUVDSF9NT0RFX1VOU1BFQ0lGSUVEEAASFwoTU1BFRUNIX01PREVfV0hJU1BFUhABEhQKEFNQRUVDSF9NT0RFX1RBTEsQAhIUChBTUEVFQ0hfTU9ERV9ZRUxMEAMqOwoEVGlsZRIUChBUSUxFX1VOU1BFQ0lGSUVEEAASDgoKVElMRV9GTE9PUhABEg0KCVRJTEVfV0FMTBACKm0KDkNoYXJhY3RlclN0YXRlEh8KG0NIQVJBQ1RFUl9TVEFURV9VTlNQRUNJRklFRBAAEhkKFUNIQVJBQ1RFUl9TVEFURV9BV0FLRRABEh8KG0NIQVJBQ1RFUl9TVEFURV9VTkNPTlNDSU9VUxACQitaKWdseXBoL3NlcnZlci9pbnRlcm5hbC9wYi9nbHlwaC92MTtnbHlwaHYxYgZwcm90bzM");

/**
 * Position is a tile coordinate. One tile is about 1 m.
 * x grows east, y grows south.
 *
 * @generated from message glyph.v1.Position
 */
export type Position = Message<"glyph.v1.Position"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message glyph.v1.Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_glyph_v1_world, 0);

/**
 * Room is a rectangular grid of tiles.
 *
 * @generated from message glyph.v1.Room
 */
export type Room = Message<"glyph.v1.Room"> & {
  /**
   * @generated from field: uint32 width = 1;
   */
  width: number;

  /**
   * @generated from field: uint32 height = 2;
   */
  height: number;

  /**
   * Row-major: the tile at (x, y) is tiles[y * width + x].
   *
   * @generated from field: repeated glyph.v1.Tile tiles = 3;
   */
  tiles: Tile[];
};

/**
 * Describes the message glyph.v1.Room.
 * Use `create(RoomSchema)` to create a new message.
 */
export const RoomSchema: GenMessage<Room> = /*@__PURE__*/
  messageDesc(file_glyph_v1_world, 1);

/**
 * @generated from message glyph.v1.Character
 */
export type Character = Message<"glyph.v1.Character"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: glyph.v1.Position position = 3;
   */
  position?: Position | undefined;

  /**
   * @generated from field: glyph.v1.CharacterState state = 4;
   */
  state: CharacterState;
};

/**
 * Describes the message glyph.v1.Character.
 * Use `create(CharacterSchema)` to create a new message.
 */
export const CharacterSchema: GenMessage<Character> = /*@__PURE__*/
  messageDesc(file_glyph_v1_world, 2);

/**
 * Direction of a step (ADR 023: 8 ways).
 *
 * @generated from enum glyph.v1.Direction
 */
export enum Direction {
  /**
   * @generated from enum value: DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIRECTION_NORTH = 1;
   */
  NORTH = 1,

  /**
   * @generated from enum value: DIRECTION_NORTH_EAST = 2;
   */
  NORTH_EAST = 2,

  /**
   * @generated from enum value: DIRECTION_EAST = 3;
   */
  EAST = 3,

  /**
   * @generated from enum value: DIRECTION_SOUTH_EAST = 4;
   */
  SOUTH_EAST = 4,

  /**
   * @generated from enum value: DIRECTION_SOUTH = 5;
   */
  SOUTH = 5,

  /**
   * @generated from enum value: DIRECTION_SOUTH_WEST = 6;
   */
  SOUTH_WEST = 6,

  /**
   * @generated from enum value: DIRECTION_WEST = 7;
   */
  WEST = 7,

  /**
   * @generated from enum value: DIRECTION_NORTH_WEST = 8;
   */
  NORTH_WEST = 8,
}

/**
 * Describes the enum glyph.v1.Direction.
 */
export const DirectionSchema: GenEnum<Direction> = /*@__PURE__*/
  enumDesc(file_glyph_v1_world, 0);

/**
 * How loudly something is said (ADR 010). Each mode has its own range.
 *
 * @generated from enum glyph.v1.SpeechMode
 */
export enum SpeechMode {
  /**
   * @generated from enum value: SPEECH_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SPEECH_MODE_WHISPER = 1;
   */
  WHISPER = 1,

  /**
   * @generated from enum value: SPEECH_MODE_TALK = 2;
   */
  TALK = 2,

  /**
   * @generated from enum value: SPEECH_MODE_YELL = 3;
   */
  YELL = 3,
}

/**
 * Describes the enum glyph.v1.SpeechMode.
 */
export const SpeechModeSchema: GenEnum<SpeechMode> = /*@__PURE__*/
  enumDesc(file_glyph_v1_world, 1);

/**
 * @generated from enum glyph.v1.Tile
 */
export enum Tile {
  /**
   * @generated from enum value: TILE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TILE_FLOOR = 1;
   */
  FLOOR = 1,

  /**
   * @generated from enum value: TILE_WALL = 2;
   */
  WALL = 2,
}

/**
 * Describes the enum glyph.v1.Tile.
 */
export const TileSchema: GenEnum<Tile> = /*@__PURE__*/
  enumDesc(file_glyph_v1_world, 2);

/**
 * @generated from enum glyph.v1.CharacterState
 */
export enum CharacterState {
  /**
   * @generated from enum value: CHARACTER_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CHARACTER_STATE_AWAKE = 1;
   */
  AWAKE = 1,

  /**
   * Disconnected; the body stays in the world (ADR 014).
   *
   * @generated from enum value: CHARACTER_STATE_UNCONSCIOUS = 2;
   */
  UNCONSCIOUS = 2,
}

/**
 * Describes the enum glyph.v1.CharacterState.
 */
export const CharacterStateSchema: GenEnum<CharacterState> = /*@__PURE__*/
  enumDesc(file_glyph_v1_world, 3);

